//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComisionesCM.ProxyConsultas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyConsultas.ISvcConsultasDSW")]
    public interface ISvcConsultasDSW {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcConsultasDSW/IniciarDatosConexion", ReplyAction="http://tempuri.org/ISvcConsultasDSW/IniciarDatosConexionResponse")]
        void IniciarDatosConexion(string datosCon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcConsultasDSW/LeerClientes", ReplyAction="http://tempuri.org/ISvcConsultasDSW/LeerClientesResponse")]
        System.Collections.Generic.List<deSoft.dSWin.Entidades.ConsultaCliente> LeerClientes(int idEmpresa, int idDelegacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcConsultasDSW/LeerArticulos", ReplyAction="http://tempuri.org/ISvcConsultasDSW/LeerArticulosResponse")]
        System.Collections.Generic.List<deSoft.dSWin.Entidades.BuscaArticulo> LeerArticulos(int idEmpresa, int idDelegacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcConsultasDSW/CrearComisiones", ReplyAction="http://tempuri.org/ISvcConsultasDSW/CrearComisionesResponse")]
        System.Collections.Generic.List<deSoft.dSWin.Entidades.ComisionArti> CrearComisiones(System.Nullable<int> idEmpresa, System.Nullable<int> idDelegacion, System.DateTime fecIni, System.DateTime fecFin, System.Nullable<int> idVendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcConsultasDSW/LeerCantidadesReparto", ReplyAction="http://tempuri.org/ISvcConsultasDSW/LeerCantidadesRepartoResponse")]
        System.Collections.Generic.List<deSoft.dSWin.Entidades.CantidadesRepartidor> LeerCantidadesReparto(System.Nullable<int> idEmpresa, System.Nullable<int> idDelegacion, System.DateTime fecIni, System.DateTime fecFin, System.Nullable<int> idRepartidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcConsultasDSW/LeerIncidenciasVentas", ReplyAction="http://tempuri.org/ISvcConsultasDSW/LeerIncidenciasVentasResponse")]
        System.Collections.Generic.List<EntidadesConsultas.IncidenciaVentas> LeerIncidenciasVentas(System.Nullable<int> idEmpresa, System.Nullable<int> idDelegacion, System.DateTime fecIni, System.DateTime fecFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcConsultasDSW/LeerIncidenciasRepartos", ReplyAction="http://tempuri.org/ISvcConsultasDSW/LeerIncidenciasRepartosResponse")]
        System.Collections.Generic.List<EntidadesConsultas.IncidenciaReparto> LeerIncidenciasRepartos(System.Nullable<int> idEmpresa, System.Nullable<int> idDelegacion, System.DateTime fecIni, System.DateTime fecFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcConsultasDSW/LeerVentas", ReplyAction="http://tempuri.org/ISvcConsultasDSW/LeerVentasResponse")]
        System.Collections.Generic.List<deSoft.dSWin.Entidades.InfVentasClientes> LeerVentas(System.Nullable<int> idEmpresa, System.Nullable<int> idDelegacion, System.DateTime fecIni, System.DateTime fecFin, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcConsultasDSW/LeerVentasArti", ReplyAction="http://tempuri.org/ISvcConsultasDSW/LeerVentasArtiResponse")]
        System.Collections.Generic.List<EntidadesConsultas.VentasArti> LeerVentasArti(System.Nullable<int> idEmpresa, System.Nullable<int> idDelegacion, System.DateTime fecIni, System.DateTime fecFin, string vendedores, bool porVendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcConsultasDSW/LeerComisionesRepDet", ReplyAction="http://tempuri.org/ISvcConsultasDSW/LeerComisionesRepDetResponse")]
        System.Collections.Generic.List<EntidadesConsultas.ComisionRep> LeerComisionesRepDet(out string nombreTabla, EntidadesConsultas.FiltroCon filtro, short tamPag, System.Nullable<int> idInicio, string tablaEntrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcConsultasDSW/LeerCompVC", ReplyAction="http://tempuri.org/ISvcConsultasDSW/LeerCompVCResponse")]
        System.Collections.Generic.List<EntidadesConsultas.CompVC> LeerCompVC(out string nombreTabla, EntidadesConsultas.FiltroCon filtro, short tamPag, System.Nullable<int> idInicio, string tablaEntrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcConsultasDSW/LeerVentasDias", ReplyAction="http://tempuri.org/ISvcConsultasDSW/LeerVentasDiasResponse")]
        System.Collections.Generic.List<EntidadesConsultas.InfVentasClientesD> LeerVentasDias(System.Nullable<int> idEmpresa, System.Nullable<int> idDelegacion, System.DateTime fecIni, System.DateTime fecFin);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISvcConsultasDSWChannel : ComisionesCM.ProxyConsultas.ISvcConsultasDSW, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SvcConsultasDSWClient : System.ServiceModel.ClientBase<ComisionesCM.ProxyConsultas.ISvcConsultasDSW>, ComisionesCM.ProxyConsultas.ISvcConsultasDSW {
        
        public SvcConsultasDSWClient() {
        }
        
        public SvcConsultasDSWClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SvcConsultasDSWClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvcConsultasDSWClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvcConsultasDSWClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void IniciarDatosConexion(string datosCon) {
            base.Channel.IniciarDatosConexion(datosCon);
        }
        
        public System.Collections.Generic.List<deSoft.dSWin.Entidades.ConsultaCliente> LeerClientes(int idEmpresa, int idDelegacion) {
            return base.Channel.LeerClientes(idEmpresa, idDelegacion);
        }
        
        public System.Collections.Generic.List<deSoft.dSWin.Entidades.BuscaArticulo> LeerArticulos(int idEmpresa, int idDelegacion) {
            return base.Channel.LeerArticulos(idEmpresa, idDelegacion);
        }
        
        public System.Collections.Generic.List<deSoft.dSWin.Entidades.ComisionArti> CrearComisiones(System.Nullable<int> idEmpresa, System.Nullable<int> idDelegacion, System.DateTime fecIni, System.DateTime fecFin, System.Nullable<int> idVendedor) {
            return base.Channel.CrearComisiones(idEmpresa, idDelegacion, fecIni, fecFin, idVendedor);
        }
        
        public System.Collections.Generic.List<deSoft.dSWin.Entidades.CantidadesRepartidor> LeerCantidadesReparto(System.Nullable<int> idEmpresa, System.Nullable<int> idDelegacion, System.DateTime fecIni, System.DateTime fecFin, System.Nullable<int> idRepartidor) {
            return base.Channel.LeerCantidadesReparto(idEmpresa, idDelegacion, fecIni, fecFin, idRepartidor);
        }
        
        public System.Collections.Generic.List<EntidadesConsultas.IncidenciaVentas> LeerIncidenciasVentas(System.Nullable<int> idEmpresa, System.Nullable<int> idDelegacion, System.DateTime fecIni, System.DateTime fecFin) {
            return base.Channel.LeerIncidenciasVentas(idEmpresa, idDelegacion, fecIni, fecFin);
        }
        
        public System.Collections.Generic.List<EntidadesConsultas.IncidenciaReparto> LeerIncidenciasRepartos(System.Nullable<int> idEmpresa, System.Nullable<int> idDelegacion, System.DateTime fecIni, System.DateTime fecFin) {
            return base.Channel.LeerIncidenciasRepartos(idEmpresa, idDelegacion, fecIni, fecFin);
        }
        
        public System.Collections.Generic.List<deSoft.dSWin.Entidades.InfVentasClientes> LeerVentas(System.Nullable<int> idEmpresa, System.Nullable<int> idDelegacion, System.DateTime fecIni, System.DateTime fecFin, string tipo) {
            return base.Channel.LeerVentas(idEmpresa, idDelegacion, fecIni, fecFin, tipo);
        }
        
        public System.Collections.Generic.List<EntidadesConsultas.VentasArti> LeerVentasArti(System.Nullable<int> idEmpresa, System.Nullable<int> idDelegacion, System.DateTime fecIni, System.DateTime fecFin, string vendedores, bool porVendedor) {
            return base.Channel.LeerVentasArti(idEmpresa, idDelegacion, fecIni, fecFin, vendedores, porVendedor);
        }
        
        public System.Collections.Generic.List<EntidadesConsultas.ComisionRep> LeerComisionesRepDet(out string nombreTabla, EntidadesConsultas.FiltroCon filtro, short tamPag, System.Nullable<int> idInicio, string tablaEntrada) {
            return base.Channel.LeerComisionesRepDet(out nombreTabla, filtro, tamPag, idInicio, tablaEntrada);
        }
        
        public System.Collections.Generic.List<EntidadesConsultas.CompVC> LeerCompVC(out string nombreTabla, EntidadesConsultas.FiltroCon filtro, short tamPag, System.Nullable<int> idInicio, string tablaEntrada) {
            return base.Channel.LeerCompVC(out nombreTabla, filtro, tamPag, idInicio, tablaEntrada);
        }
        
        public System.Collections.Generic.List<EntidadesConsultas.InfVentasClientesD> LeerVentasDias(System.Nullable<int> idEmpresa, System.Nullable<int> idDelegacion, System.DateTime fecIni, System.DateTime fecFin) {
            return base.Channel.LeerVentasDias(idEmpresa, idDelegacion, fecIni, fecFin);
        }
    }
}
